<!DOCTYPE html>
<html>
<head>
	<title>Sistema Gerenciador de Tarefas</title>
	<style type="text/css">
		#top{
			background-color: #aaa;
		}
	</style>
</head>
<body>
	<div id="top">
		<h1>Sistemas Gerenciador de Tarefas</h1>
	</div>
	<div id ="left">
		
	</div>
	<div id = "content">
		<?php echo  $this->content();?>
	</div>
</body>
</html>
<!--Titulo-->
<!--Formulário-->
<!-- Nome (input text)-->
<!-- Descrição (input text)-->
<!-- Prazo (input text)-->
<!--Prioridade (option)-->
<!-- Finalizada (checkbox)-->
<!-- Tabela-->